#!/bin/bash

if [ -f /home/function.go ]; then
	FUNCTION=HelloHTTP
  RUNTIME=go111
fi

if [ -f /home/index.js ]; then
	FUNCTION=helloHttp
  RUNTIME=nodejs8
fi

if [ -f /home/main.py ]; then
	FUNCTION=hello_http
  RUNTIME=python37
fi

gcloud functions describe $FUNCTION
if [ $? -ne 0 ]; then
    fail-message "Could not find a function that triggers on HTTP requests. Type 'hint' if you are stuck."
    exit 1
fi

gcloud functions describe $FUNCTION --format=json | jq -e '.entryPoint != null and .runtime != null and .httpsTrigger.url != null'
if [ $? -ne 0 ]; then
    fail-message "Could not find a function that triggers on HTTP requests. Type 'hint' if you are stuck."
    exit 1
fi