#!/bin/bash
gcloud functions list --limit 1 --format=json | jq -e '.[] | .entryPoint != null and .runtime != null and .httpsTrigger.url != null'
if [ $? -ne 0 ]; then
    fail-message "Could not find a function that triggers on HTTP requests"
    exit 1
fi