#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -f /home/function.go ]; then
  export FUNCTION=HelloHTTP
  export RUNTIME=go111
fi

if [ -f /home/index.js ]; then
  export FUNCTION=helloHttp
  export RUNTIME=nodejs8
fi

if [ -f /home/main.py ]; then
  export FUNCTION=hello_http
  export RUNTIME=python37
fi

source /root/.instruqt/.translationsenv

echo "$DEPLOYMENT_HELP" > /root/.instruqt/help.txt
echo "$DEPLOYMENT_HINT" > /root/.instruqt/hint.txt

cat <<EOF > /root/package.json
{
  "scripts": {
    "start": "node index.js"
  },
  "license": "Apache-2.0",
  "dependencies": {
    "cowsay": "^1.4.0"
  }
}
EOF

echo "exports.cowsay = (req, res) => {res.end(require('cowsay').say({text:\`\${req.query.text || 'Google Cloud Functions are awesome'}\`}))}" > /root/index.js
echo "nohup gcloud functions deploy cowsay --source=/root/ --trigger-http > /dev/null 2>&1 &" >> /root/.instruqt/.customrc

set-workdir /home
