#!/bin/bash
if [ -f /home/function.go ]; then
	FUNCTION=HelloHTTP
  RUNTIME=go111
fi

if [ -f /home/index.js ]; then
	FUNCTION=helloHttp
  RUNTIME=nodejs8
fi

if [ -f /home/main.py ]; then
	FUNCTION=hello_http
  RUNTIME=python37
fi
grep "gcloud functions logs read $FUNCTION" ~/.bash_history
if [ $? -ne 0 ]; then
    fail-message "Functions logs have not been read with gcloud. Type 'hint' if you are stuck."
    exit 1
fi