#!/bin/bash
cat <<EOF > /root/help.txt
Use gcloud to read the logs from your function.

EOF

if [ -f /home/function.go ]; then
	FUNCTION=HelloHTTP
  RUNTIME=go111
fi

if [ -f /home/index.js ]; then
	FUNCTION=helloHttp
  RUNTIME=nodejs8
fi

if [ -f /home/main.py ]; then
	FUNCTION=hello_http
  RUNTIME=python37
fi

cat <<EOF > /root/hint.txt
To read all your functions logs, use:
 gcloud functions logs read

To read logs from your specific function, use:
 gcloud functions logs read $FUNCTION

EOF

set-workdir /home