#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
cat <<EOF > /root/help.txt
Use gcloud to read the logs from your function.

EOF

if [ -f /home/function.go ]; then
	FUNCTION=HelloHTTP
  RUNTIME=go111
fi

if [ -f /home/index.js ]; then
	FUNCTION=helloHttp
  RUNTIME=nodejs8
fi

if [ -f /home/main.py ]; then
	FUNCTION=hello_http
  RUNTIME=python37
fi

cat <<EOF > /root/hint.txt
To read all your functions logs, use:
 gcloud functions logs read

To read logs from your specific function, use:
 gcloud functions logs read $FUNCTION

EOF

set-workdir /home