#!/bin/bash

if [ ! -f /usr/local/bin/answer.txt ]; then
    fail-message "You haven't answered yet! You must run the \"answer\" command and press ENTER"
    exit 1
fi

ANSWER=$(cat /usr/local/bin/answer.txt)

ALMOST_CORRECT="french bulldog"
if [[ "$ALMOST_CORRECT" == "$ANSWER" ]]; then
    fail-message "You're close! There is one other dog breed which is more prominent"
    exit 1
fi

CORRECT="boston terrier"
if [[ "$CORRECT" != "$ANSWER" ]]; then
    fail-message "Your answer is incorrect! Type \"hint\" if you are stuck."
    exit 1
fi
