#!/bin/bash

# Delete the answer file
rm /usr/local/bin/answer.txt

# Delete the multiple choices file
rm /root/choices.txt

# Delete the help file
rm /root/help.txt

# Delete the help image
rm /root/help.png

# Delete the hint file
rm /root/hint.txt

# Delete the challenge assets
rm /home/doggo1.png
