#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Starts the user in the /home directory
set-workdir /home
source /root/.translationsenv

# Put the help text in help.txt
echo "$ANALYZING_IMAGES_HELP" > /root/help.txt

echo "$ANALYZING_IMAGES_HINT" > /root/hint.txt

echo "$ANALYSZING_IMAGES_CHOICES" > /root/choices.txt

# Remove hint and multiple choice in hard mode
if [[ "$INSTRUQT_DIFFICULTY" = "hard" ]]; then
    rm /root/choices.txt
    echo $DIFFICULTY_HARD_HINT > /root/hint.txt
fi

cp /root/images/doggo1.png /home/doggo1.png
cp /root/images/doggo1.png /root/help.png
