#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

bq show $DATASET_ID.road_trip
if [ $? -ne 0 ]; then
  fail-message "$CREATE_TABLE_AND_LOAD_DATA_FAIL_NO_TABLE"
  exit 1
fi

OUTPUT=$(bq show --schema $DATASET_ID.road_trip)
if [ $? -ne 0 ]; then
  fail-message "$CREATE_TABLE_AND_LOAD_DATA_FAIL_NO_SCHEMA"
  exit 1
fi

echo $OUTPUT | jq -e 'sort_by(.name) | .[0].name == "date" and .[1].name == "id" and .[2].name == "lat" and .[3].name == "long" and .[4].name == "place"'
if [ $? -ne 0 ]; then
  fail-message "$CREATE_TABLE_AND_LOAD_DATA_FAIL_WRONG_FIELDS"
  exit 1
fi

echo $OUTPUT | jq -e 'sort_by(.name) | .[0].type == "DATE" and .[1].type == "INTEGER" and .[2].type == "FLOAT" and .[3].type == "FLOAT" and .[4].type == "STRING"'
if [ $? -ne 0 ]; then
  fail-message "$CREATE_TABLE_AND_LOAD_DATA_FAIL_WRONG_TYPES"
  exit 1
fi

COUNT=$(bq query --format=prettyjson 'SELECT count(1) as num FROM `'$DATASET_ID'.road_trip`' | jq -r '.[].num')
if [ "$COUNT" -ne "16" ]; then
  echo ""
  fail-message "$CREATE_TABLE_AND_LOAD_DATA_FAIL_NO_DATA"
  exit 1
fi
