#!/bin/bash

# Put the user in the /home directory
set-workdir /home

# Put the help text in help.txt
cat <<EOF > /home/help.txt

# Your Quest
-------------------------------

The puppy in "videos/video1.mp4" wants to be your friend! But only if you can
find her. Using "gcloud", send this good girl through Google's Video
Intelligence API and report back the starting time in seconds (for example, "7")
when she appears.

When you think you know the answer, type "answer" and press ENTER.

*HINT* Use the command "gcloud ml video" to get started.

EOF

mv /home/videos/video1.png /root/help.png
