#!/bin/bash

# Put the user in the /home directory
set-workdir /home

# Put the help text in help.txt
cat <<EOF > /root/help.txt
The puppy in "video1.mp4" wants to be your friend! But only if you can
find her. Using "gcloud", send this good girl through Google's Video
Intelligence API and report back the starting time in seconds (for example, "7")
when she appears.

*HINT* Use the command "gcloud ml video" to get started.

When you think you know the answer, type "answer" and press ENTER.
EOF

cat <<EOF > /root/hint.txt
Try running the following command:

    gcloud ml video detect-labels video1.mp4 | more

Look for the value of "startTimeOffset" where the entity "description" is
"dog" or "puppy"
EOF

cp /root/videos/video1.mp4 /home/video1.mp4
cp /root/videos/video1.png /root/help.png
