steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
        [
          "build", "-t", "gcr.io/$PROJECT_ID/gcf:$_TAG",
          ".",
        ]
substitutions:   
  _TAG: 1.0.3
images: ['gcr.io/$PROJECT_ID/gcf:$_TAG']