steps:
    - name: "gcr.io/cloud-builders/docker"
      args:
        [
          "build", "-t", "europe-west1-docker.pkg.dev/instruqt-shadow-resources/library/cloud-ml-apis:$_TAG",
          ".",
        ]
substitutions:   
  _TAG: 1.0.0
images: ['europe-west1-docker.pkg.dev/instruqt-shadow-resources/library/cloud-ml-apis:$_TAG']