#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# A new service should have been deployed 
COUNT=$(gcloud run services list --format json | jq length)
if [ "$COUNT" -lt "2" ]; then
    fail-message "Expected an additional Cloud Run service"
    exit 1
fi

# An anonymous request should have been denied
COUNT_403=$(gcloud logging read \
"httpRequest.status=403 AND \
resource.type=\"cloud_run_revision\"" --format=json | jq length)
if [ "$COUNT_403" -eq "0" ]; then
    fail-message "There was no denied request (HTTP 403) detected to the service. This might take a while to detect, please try again in a bit."
    exit 1
fi

