#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Challenge objective
# Deploy a protected service

echo "$AUTHENTICATED_SERVICE_HELP" > /root/.instruqt/help.txt
echo "$AUTHENTICATED_SERVICE_HINT" > /root/.instruqt/hint.txt

set-workdir /home

cat <<EOF > /root/.instruqt/help.txt
You can also protect Cloud Run services from public access. This is what 
you need to do:

1. Deploy the same image (\$IMAGE_TAG) as a new service with a different 
name. This time, do not allow unauthenticated access.

2. Send a request to the service with curl, to show you don't have 
permission to call it anonymously. 

Hit the "Check" button when you are done.

EOF

cat <<EOF > /root/.instruqt/hint.txt
Deploy the same image as a new service with a different name: 

gcloud run deploy secret-fortune --image \$IMAGE_TAG --no-allow-unauthenticated

> Send a request to the new service and watch it being denied:

URL=\$(gcloud run services describe secret-fortune --format="value(status.url)")
curl \$URL
EOF