#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kubectl get service frontend-service -n challenge
if [ $? -ne 0 ]; then
    fail-message "$SERVICE_FAIL_NO_SERVICE"
    exit 1
fi


kubectl get service frontend-service -n challenge -o json | jq -e '.spec.selector != null and .spec.selector.role != null and .spec.selector.role == "frontend" and .spec.type == "LoadBalancer"'
if [ $? -ne 0 ]; then
    fail-message "$SERVICE_FAIL_CONFIGURATION"
    exit 1
fi