#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

REQ_COUNT=$(kubectl logs service/istio-ingress istio-proxy -n gke-system | \
while read -r line; do \
  echo "$line" | \
  jq '. | select( ."logging.googleapis.com/trace" != "-" and .httpRequest.userAgent != "Knative-Ingress-Probe" ) | ."logging.googleapis.com/trace"' \
  2>/dev/null
done | \
wc -l)

if [ "$REQ_COUNT" -eq "0" ]; then
    fail-message "$DEPLOY_SERVICE_FAIL"
    exit 1
fi