#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /root/.instruqt/.translationsenv

echo "$GETTING_STARTED_HELP" > /root/.instruqt/help.txt
echo "$GETTING_STARTED_HINT" > /root/.instruqt/hint.txt

set-workdir /home

cat <<EOF > /home/service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: INSERT NAME HERE 
spec:
  template:
    spec:     
      containers:
      - image: gcr.io/cloudrun/hello
EOF

gcloud config set run/platform gke
gcloud config set run/region us-central1
gcloud config set compute/zone us-central1-a
gcloud beta container clusters create knative \
 --addons HttpLoadBalancing,CloudRun \
 --release-channel rapid \
 --machine-type e2-small \
 --num-nodes 2 \
 --zone us-central1-a \
 --enable-stackdriver-kubernetes \
 --enable-ip-alias \
 --async
