#!/bin/bash 
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
source /etc/profile.d/google-adc.sh

# check that a job with name "batchjob" exists
BATCHJOB=$(gcloud beta run jobs list --region $(gcloud config get run/region) --format yaml | grep -w batchjob | head -1 | sed 's/name: //g')
if [ -z "$BATCHJOB" ]; then
    fail-message "You do not appear to have created any Cloud Run Jobs with the name 'batchjob'."
    exit 1
fi

# check that the correct image is being used
IMAGE=$(gcloud beta run jobs describe batchjob --format yaml | grep client.knative.dev/user-image | head -1 | sed 's/client.knative.dev\/user-image: //g')
if [[ ${IMAGE} != *"us-docker.pkg.dev/cloudrun/container/job:"* ]]; then 
    fail-message "Your Cloud Run Job does not seem to have been deployed with the correct image."
    exit 1
fi