version: "2"
containers:
- name: shell
  image: gcr.io/instruqt-shadow/cloud-storage:1.1.3
  shell: /bin/bash
  memory: 128
gcp_projects:
- name: cloud-storage
  services:
  - storage-api.googleapis.com
  - storage-component.googleapis.com
