version: "2"
containers:
- name: shell
  image: gcr.io/instruqt-shadow/cloud-storage:1.0.0
  shell: /bin/bash
  memory: 128
gcp_projects:
- name: cloud-functions
  services:
  - storage-api.googleapis.com
