version: "2"
containers:
- name: shell
  image: gcr.io/instruqt-shadow/cloud-storage:2.2.7
  shell: /bin/bash
  memory: 512
  environment:
    INSTRUQT_LANGUAGE_CODE: en
gcp_projects:
- name: cloud-storage
  services:
  - storage-api.googleapis.com
  - storage-component.googleapis.com
