#!/bin/bash
kubectl get deployment app -n challenge
if [ $? -ne 0 ]; then
    fail-message "Could not find Deployment called 'app' in the namespace 'challenge'. Type 'hint' if you are stuck."
    exit 1
fi


kubectl get deployment app -n challenge -o json | jq -e '.spec.template.metadata.labels != null and .spec.template.metadata.labels.name != null and .spec.template.metadata.labels.name == "app" and .spec.template.spec.containers[0].image == "gcr.io/instruqt-shadow/challenge"'
if [ $? -ne 0 ]; then
    fail-message "Pods in the Deployment are not labeled with 'name=app'. Type 'hint' if you are stuck."
    exit 1
fi