#!/bin/bash

echo "source /usr/lib/google-cloud-sdk/completion.bash.inc" >> /root/.bashrc

cat <<EOF > /root/help.txt
We have provided you with a function written in the different languages (Node.js, Python and Golang) that are supported by Google Cloud Functions.

Open one of the functions using your favourite editor (vi, vim, nano or install your own) and change it, so it returns "Hello, Google!" instead of "Hello, World!".

EOF

set-workdir /home

cat <<EOF > /home/function.go
// Package helloworld provides a set of Cloud Function samples.
package helloworld

import (
	"fmt"
	"net/http"
)

// HelloHTTP is an HTTP Cloud Function
func HelloHTTP(w http.ResponseWriter, r *http.Request) {
	// Print to stdout
	fmt.Print("This is a log!")
	fmt.Fprint(w, "Hello, World!")
}
EOF

cat <<EOF > /home/index.js
exports.helloHttp = (req, res) => {
  // Print to stdout
  console.log('This is a log!')
  res.send('Hello, World!');
};
EOF

cat <<EOF > /home/main.py
def hello_http(request):
    # Print to stdout
    print('This is a log!')
    return 'Hello, World!'
EOF