#!/bin/bash

echo "source /usr/lib/google-cloud-sdk/completion.bash.inc" >> .bashrc

cat <<EOF > function.go
// Package helloworld provides a set of Cloud Function samples.
package helloworld

import (
	"fmt"
	"net/http"
)

// HelloHTTP is an HTTP Cloud Function
func HelloHTTP(w http.ResponseWriter, r *http.Request) {
	// Print to stdout
	fmt.Print("This is a log!")
	fmt.Fprint(w, "Hello, World!")
}
EOF

cat <<EOF > index.js
exports.helloHttp = (req, res) => {
  // Print to stdout
  console.log('This is a log!')
  res.send('Hello, World!');
};
EOF

cat <<EOF > main.py
def hello_http(request):
    # Print to stdout
    print('This is a log!')
    return 'Hello, World!'
EOF