#!/bin/bash
set -euxo pipefail

gcloud beta container clusters create "default" \
  --zone "europe-west1-b" \
  --no-enable-basic-auth \
  --cluster-version "1.22.12-gke.2300" \
  --release-channel "None" \
  --machine-type "e2-small" \
  --image-type "COS_CONTAINERD" \
  --disk-type "pd-standard" --disk-size "10" \
  --metadata disable-legacy-endpoints=true \
  --scopes "https://www.googleapis.com/auth/devstorage.read_only","https://www.googleapis.com/auth/logging.write","https://www.googleapis.com/auth/monitoring","https://www.googleapis.com/auth/servicecontrol","https://www.googleapis.com/auth/service.management.readonly","https://www.googleapis.com/auth/trace.append" \
  --spot --num-nodes "1" \
  --no-enable-intra-node-visibility \
  --enable-ip-alias \
  --default-max-pods-per-node "110" \
  --no-enable-master-authorized-networks \
  --addons HttpLoadBalancing,GcePersistentDiskCsiDriver \
  --no-enable-autoupgrade \
  --no-enable-autorepair \
  --max-surge-upgrade 1 \
  --max-unavailable-upgrade 0 \
  --enable-shielded-nodes \
  --node-locations "europe-west1-b" 

gcloud config set compute/zone europe-west1-b
gcloud container clusters get-credentials default