#!/bin/bash
set -euxo pipefail

mkdir -p /root/cowsay 

cat <<EOF > /root/cowsay/package.json
{
  "scripts": {
    "start": "node index.js"
  },
  "license": "Apache-2.0",
  "dependencies": {
    "cowsay": "^1.4.0"
  }
}
EOF

echo "exports.cowsay = (req, res) => {res.end(require('cowsay').say({text:\`\${req.query.text || 'Google Cloud Functions are awesome'}\`}))}" > /root/cowsay/index.js

# Build script with three retries
gcloud functions deploy cowsay --runtime nodejs12 --trigger-http --allow-unauthenticated --source /root/cowsay

