#!/bin/bash

# Delete the answer file
rm /usr/local/bin/answer.txt

# Delete the help file
rm /root/help.txt

# Delete the hint file
rm /root/hint.txt

# Delete the challenge assets
rm /home/quote1.wav
rm /home/quote2.wav
rm /home/quote3.wav
