#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Put the user in the /home directory
set-workdir /home

# Put the help text in help.txt
echo "$RECOGNIZING_AUDIO_HELP" > /root/help.txt

echo "$RECOGNIZING_AUDIO_HINT" > /root/hint.txt

cp /root/images/raptor.png /root/hint.png

echo "$RECOGNIZING_AUDIO_CHOICES" > /root/choices.txt

# Remove hint and multiple choice in hard mode
if [[ "$INSTRUQT_DIFFICULTY" = "hard" ]]; then
    rm /root/choices.txt
    echo $DIFFICULTY_HARD_HINT > /root/hint.txt
fi

cp /root/audio/quote1.wav /home/quote1.wav
cp /root/audio/quote2.wav /home/quote2.wav
cp /root/audio/quote3.wav /home/quote3.wav
