#!/bin/bash

# Put the user in the /home directory
set-workdir /home

# Put the help text in help.txt
cat <<EOF > /root/help.txt
There are three audio files: "quote1.wav", "quote2.wav",
and "quote3.wav". Test your pop culture knowledge by identifying
the undeniably classic 90's movie these quotes are from. Convert the audio into
text using the Speech to Text API and report back with the title of the film.

*HINT* Use the command "gcloud ml speech" to get started.

When you think you know the answer, type "answer" and press ENTER.
EOF

cat <<EOF > /root/hint.txt
Try running the following command:

    gcloud ml speech recognize quote1.wav --language-code=en

Run the same command using "quote2.wav" and "quote3.wav". If you don't
recognize the movie, enter the quotes into google.com and make plans to 
watch the film immediately.
EOF

cp /root/audio/quote1.wav /home/quote1.wav
cp /root/audio/quote2.wav /home/quote2.wav
cp /root/audio/quote3.wav /home/quote3.wav
