#!/bin/bash

# Put the user in the /home directory
set-workdir /home

# Put the help text in help.txt
cat <<EOF > /root/help.txt
There are three audio files: "quote1.wav", "quote2.wav",
and "quote3.wav". Test your pop culture knowledge by identifying
the undeniably classic 90's movie these quotes are from. Convert the audio into
text using the Speech to Text API and report back with the title of the film.

*HINT* Type "gcloud ml speech" to get started.
EOF

cat <<EOF > /root/hint.txt
Try running the following command:

    gcloud ml speech recognize quote1.wav --language-code=en

Run the same command using "quote2.wav" and "quote3.wav".

If you don't recognize the movie, run the quotes using the googler script and that
should help narrow it down:

    googler "this is a movie quote!"

EOF

cp /root/images/raptor.png /root/hint.png

cat <<EOF > /root/choices.txt
What movie are these quotes from?
Silence of the Lambs
Jurassic Park
The Room
Pulp Fiction
Foreset Gump
EOF

# Remove hint and multiple choice in hard mode
if [[ "$INSTRUQT_DIFFICULTY" = "hard" ]]; then
    rm /root/choices.txt
    echo "If you need a hint, maybe you should try an EASIER difficulty :)" > /root/hint.txt
fi

cp /root/audio/quote1.wav /home/quote1.wav
cp /root/audio/quote2.wav /home/quote2.wav
cp /root/audio/quote3.wav /home/quote3.wav
