#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Challenge objective
# Look at the files and execute response.sh

export SECRET_SERVICE_NAME=$(gcloud logging read \
"httpRequest.status=403 AND \
resource.type=\"cloud_run_revision\"" --format=json | jq -r .[0].resource.labels.service_name)

export SECRET_SERVICE_URL=$(gcloud run services describe $SECRET_SERVICE_NAME --format="value(status.url)")
echo "export SECRET_SERVICE_URL=$SECRET_SERVICE_URL" >> /root/.instruqt/.customrc

source /root/.instruqt/.translationsenv

echo "$CALL_AUTHENTICATED_SERVICE_HELP" > /root/.instruqt/help.txt
echo "$CALL_AUTHENTICATED_SERVICE_HINT" > /root/.instruqt/hint.txt

set-workdir /home
