version: "3"
containers:
- name: shell
  image: gcr.io/instruqt-shadow/cloud-run-track-one:0.0.1
  shell: /bin/bash
  environment:
    INSTRUQT_LANGUAGE_CODE: en
  memory: 128
gcp_projects:
- name: cloud-run
  services:
  - cloudresourcemanager.googleapis.com
  - cloudbuild.googleapis.com
  - run.googleapis.com
  roles: []
