version: "3"
containers:
- name: shell
  image: europe-west1-docker.pkg.dev/instruqt-shadow-resources/library/cloud-ml-apis:1.0.0
  shell: /bin/bash --login
  environment:
    INSTRUQT_LANGUAGE_CODE: en
  memory: 256
gcp_projects:
- name: default
  services:
  - vision.googleapis.com
  - speech.googleapis.com
  - videointelligence.googleapis.com
  - dlp.googleapis.com
  roles: []