#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Challenge objective
# Deploy the container to Cloud Run

# Make sure to use the container IMAGE_TAG that was pushed by 
# the player
export IMAGE_TAG=$(gcloud container images list --format json | jq -r .[0].name)
echo "export IMAGE_TAG=$IMAGE_TAG" >> /root/.instruqt/.customrc


echo "$DEPLOY_IMAGE_HELP" > /root/.instruqt/help.txt
echo "$DEPLOY_IMAGE_HINT" > /root/.instruqt/hint.txt

set-workdir /home

gcloud config set run/platform managed
gcloud config set run/region us-central1

cat <<EOF > /root/.instruqt/help.txt
The next step is to deploy the image as service to Cloud Run using 
"gcloud run deploy".

The tag for the image you just built is in the environment variable 
"\$IMAGE_TAG". Feel free to name the services however you like.

1. Give the service you create public access by allowing unauthenticated 
invocations.

2. Prove that your service works by calling the URL.

Hit the "Check" button when you are done.

EOF

cat <<EOF > /root/.instruqt/hint.txt
Deploy your image to Cloud Run to create the "fortune" service. 

gcloud run deploy fortune --image \$IMAGE_TAG --allow-unauthenticated

Call the URL using curl
URL=\$(gcloud run services describe fortune --format="value(status.url)")
curl \$URL
EOF