#!/bin/bash

if [ ! -f /usr/local/bin/answer.txt ]; then
    fail-message "You haven't answered yet! You must run the \"answer\" command and press ENTER"
fi

ANSWER=$(cat /usr/local/bin/answer.txt)

CORRECT="jurassic park"
if [[ "$CORRECT" != "$ANSWER" ]]; then
    fail-message "Your answer is incorrect! Try running the command \"gcloud ml speech recognize files/quote1.wav --language-code=en\""
    exit 1
fi
