#!/bin/bash

# Put the user in the $HOME directory (/root)
cd $HOME

# Put the help text in help.txt
cat <<EOF > /root/help.txt
# Your Quest
-------------------------------

There are three audio files in the "files/" directory: "quote1.wav",
"quote2.wav", and "quote3.wav". Test your pop culture knowledge by identifying
the undeniably classic 90s movie these quotes are from. Convert the audio into
text using the Speech to Text API and report back with the title of the film.

When you think you know the answer, type "answer" and press ENTER.

*HINT* Use the command "gcloud ml speech" to get started.

EOF
