#!/bin/bash --login
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source /etc/profile.d/google-adc.sh
gcloud config set run/region europe-west1

echo "export IMAGE_NAME=us-docker.pkg.dev/cloudrun/container/job:latest" >> /root/.bashrc

cat <<EOF > /root/.instruqt/help.txt
To speed up the processing time for the batch job, you can parallelize different tasks. 
The image used for the job allows distributing the work into several tasks, so let's 
modify the Cloud Run Job to run 10 tasks in parallel. To specify the amount of tasks,
use the "--tasks" flag.

Since Cloud Run Jobs is still in preview, you have to use gcloud beta.

You can get started with 
"gcloud beta run jobs"

Hit the "Check" button when you are done.

EOF

cat <<EOF > /root/.instruqt/hint.txt
Hint:
----

try running:

gcloud beta run jobs update batchjob --tasks ...

replacing "..." with the amount of tasks to be executed.
EOF

# Remove hint in hard mode
if [[ "$INSTRUQT_DIFFICULTY" = "hard" ]]; then
    echo "Sorry, no hints in HARD mode" > /root/hint.txt
fi
