#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

COUNT_200=$(gcloud logging read \
"httpRequest.status=200 AND \
resource.type=\"cloud_run_revision\"" --format json | jq length)

# Expect 10 chat messages 
if [ "$COUNT_200" -lt "10" ]; then
    fail-message "$CHAT_FAIL"
    exit 1
fi
