#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SERVICE_URL=$(gcloud run services list --format=json | jq -r .[0].status.address.url)
echo "export SERVICE_URL=$SERVICE_URL" >> /root/.instruqt/.customrc

# This will return 405 method not allowed. That is expected
# and will warm up the service without changing its internal state.
curl $SERVICE_URL

source /root/.instruqt/.translationsenv

echo "$CHAT_HELP" > /root/.instruqt/help.txt
echo "$CHAT_HINT" > /root/.instruqt/hint.txt

set-workdir /home
