#!/bin/bash
ENDPOINT=$(gcloud functions list --format json | jq -r '.[0] | .entryPoint')
grep "gcloud functions call $ENDPOINT" ~/.bash_history
if [ $? -ne 0 ]; then
    fail-message "The function was not triggered manually"
    exit 1
fi