#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
URL=$(gcloud functions describe cowsay --format json | jq -r '.httpsTrigger.url')
OUTPUT=$(curl $URL?text=I%20hope%20you%20are%20having%20fun%20with%20this%20Cloud%20Functions%20challenge!)
cat <<EOF > /root/help.txt

Let's have some fun!

We have deployed a function called 'cowsay' in your project.

Here is a sample output:

$OUTPUT

Call this function using the gcloud cli

EOF

cat <<EOF > /root/hint.txt
The function you want to test is called 'cowsay'

This means you can test the function with:
gcloud functions call cowsay

EOF

set-workdir /home
