#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Challenge objective
# Build a Docker container using Cloud Build

export IMAGE_TAG="gcr.io/$(gcloud config get-value project)/fortune"
echo "export IMAGE_TAG=$IMAGE_TAG" >> /root/.instruqt/.customrc

source /root/.instruqt/.translationsenv

echo "$BUILD_IMAGE_HELP" > /root/.instruqt/help.txt
echo "$BUILD_IMAGE_HINT" > /root/.instruqt/hint.txt

set-workdir /home 


