#!/bin/sh
PROJECT=$(gcloud config list project --format=flattened | awk 'FNR == 1 {print $2}')
echo "gcloud projects add-iam-policy-binding ${PROJECT} --member serviceAccount:${PROJECT}@appspot.gserviceaccount.com --role roles/bigquery.admin &" >> /root/.customrc
echo "gcloud services enable compute.googleapis.com cloudfunctions.googleapis.com bigquery-json.googleapis.com &" >> /root/.customrc
echo "gcloud app deploy /app/GCPQuest-Companion/app.yaml -q" >> /root/.customrc
gcloud app create --region=us-central -q
gcloud config set compute/zone us-central1-c