#!/bin/sh
gcloud config set compute/zone us-central1-c && gcloud app create --region=us-central -q
cd /app/GCPQuest-Companion
gcloud app deploy -q
project=$(gcloud config list project --format=flattened | awk 'FNR == 1 {print $2}')
gcloud projects add-iam-policy-binding ${project} --member serviceAccount:${project}@appspot.gserviceaccount.com --role roles/bigquery.admin