#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Put the user in the /home directory
set-workdir /home

# Put the help text in help.txt
cat <<EOF > /root/.instruqt/help.txt
The puppy in "video1.mp4" wants to be your friend! But only if you can
find her. Using "gcloud", send this good girl through Google's Video
Intelligence API and report back the starting time in seconds (for example, "7")
when she appears.

*HINT* Type "gcloud ml video" to get started.
EOF

cat <<EOF > /root/.instruqt/hint.txt
Try running the following command:

    gcloud ml video detect-labels video1.mp4 | more

Look for the value of "startTimeOffset" where the entity "description" is
"dog" or "puppy"
EOF

cat <<EOF > /root/.instruqt/choices.txt
What is the starting time in seconds? 
1
2
6
100
EOF

# Remove hint in hard mode
if [[ "$INSTRUQT_DIFFICULTY" = "hard" ]]; then
    echo $DIFFICULTY_HARD_HINT > /root/.instruqt/hint.txt
fi

cp /root/videos/video1.mp4 /home/video1.mp4
cp /root/videos/video1.png /root/.instruqt/help.png
