#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# To the protected service, a request should have succeeded (status 200).
SECRET_SERVICE_NAME=$(gcloud logging read \
"httpRequest.status=403 AND \
resource.type=\"cloud_run_revision\"" --format=json | jq -r .[0].resource.labels.service_name)
COUNT_200=$(gcloud logging read \
"httpRequest.status=200 AND \
resource.type=\"cloud_run_revision\" AND \
resource.labels.service_name=\"$SECRET_SERVICE_NAME\"" --format=json | jq length)
if [ "$COUNT_200" -eq "0" ]; then
    fail-message "$CALL_AUTHENTICATED_SERVICE_FAIL"
    exit 1
fi
