#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
if [ -f /home/function.go ]; then
  export FUNCTION=HelloHTTP
  export RUNTIME=go111
fi

if [ -f /home/index.js ]; then
  export FUNCTION=helloHttp
  export RUNTIME=nodejs8
fi

if [ -f /home/main.py ]; then
  export FUNCTION=hello_http
  export RUNTIME=python37
fi

export U=$(gcloud functions describe ${FUNCTION} --format json | jq -r '.httpsTrigger.url')

cat <<EOF > /root/.instruqt/.customenv
export URL=$U
EOF

source /root/.instruqt/.translationsenv

echo "$HTTP_HELP" > /root/.instruqt/help.txt
echo "$HTTP_HINT" > /root/.instruqt/hint.txt

set-workdir /home