#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ ! -f ./query.sql ]; then
  echo "No query.sql file was found in this directory."
  exit 0
fi

if [ ! -s ./query.sql ]; then
  echo "The query.sql file in this directory is empty"
  exit 0
fi

bq query "$(cat query.sql)"
