#!/bin/bash --login
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set-workdir /home

source /etc/profile.d/google-adc.sh
gcloud config set run/region europe-west1

cat <<EOF > /root/.instruqt/help.txt
Now it's time to execute your newly create Cloud Run Job with the name "batchjob". 
For now, we will only execute it manually.

Since Cloud Run Jobs is still in preview, you will have to use gcloud beta.

You can get started with
"gcloud beta run"

Hit the "Check" button when you are done.

EOF

cat <<EOF > /root/.instruqt/hint.txt
Hint
----

try running:

gcloud beta run jobs execute ...

replacing "..." with the job name.
EOF

# Remove hint in hard mode
if [[ "$INSTRUQT_DIFFICULTY" = "hard" ]]; then
    echo "Sorry, no hints in HARD mode!" > /root/hint.txt
fi
