version: "2"
containers:
- name: redirect
  image: gcr.io/instruqt-shadow/redirect
  ports:
  - 80
  memory: 128
- name: shell
  image: gcr.io/instruqt-shadow/cloudjourneybootstrap
  shell: /bin/bash
  ports:
  - 80
  memory: 256
gcp_projects:
- name: gcp-project
  services:
  - cloudresourcemanager.googleapis.com
  - appengine.googleapis.com
  - storage-component.googleapis.com
  - storage-api.googleapis.com
  - serviceusage.googleapis.com
