#!/bin/bash
# Copyright 2019 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
kubectl label namespace default time=$(date '+%s') --overwrite # mark cluster as still used

EXTERNAL_IP=$(kubectl get service app -n challenge -o jsonpath="{.status.loadBalancer.ingress[*].ip}")
OUTPUT=$(curl -s $EXTERNAL_IP)

cat <<EOF > /root/.instruqt/help.txt
$COMBINED_HELP_1

$OUTPUT

$COMBINED_HELP_2

EOF

echo "$COMBINED_HINT" > /root/.instruqt/hint.txt

set-workdir /home

cat <<EOF > /home/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: challenge
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - image: gcr.io/gke-arcade/challenge
        name: app
        ports:
          - name: http
            containerPort: 3000
        env:
        - name: <?>
          valueFrom:
            configMapKeyRef:
              name:  <?>
              key:  <?>
        - name: <?>
          valueFrom:
            secretKeyRef:
              name: <?>
              key:  <?>
EOF

cat <<EOF > /root/.instruqt/.customenv
URL=$EXTERNAL_IP
EOF