#!/bin/bash
kubectl label namespace default time=$(date '+%s') --overwrite # mark cluster as still used

cat <<EOF > deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: challenge
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - image: gcr.io/instruqt-shadow/challenge
        name: app
        ports:
          - name: http
            containerPort: 3000
        env:
        - name: <?>
          valueFrom:
            configMapKeyRef:
              name:  <?>
              key:  <?>
        - name: <?>
          valueFrom:
            secretKeyRef:
              name: <?>
              key:  <?>
EOF